"""initial schema

Revision ID: 02d6a226e1f3
Revises: 
Create Date: 2026-10-05 18:15:11.062294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

import app.models  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '02d6a226e1f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ddragon_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('champion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_champion_key'), ['key'], unique=True)

    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('riot_game_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('riot_tag_line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('puuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_puuid'), ['puuid'], unique=False)

    op.create_table('riotmatch',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('game_start', app.models.UTCDateTime(), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options_per_player', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('started_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('ended_at', app.models.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_mode', sa.Boolean(), nullable=False),
    sa.Column('active_run_id', sa.Integer(), nullable=True),
    sa.Column('allowed_queue_ids', sa.JSON(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('remake_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('last_used_player_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['active_run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challengegame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('riot_match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prev_win_count', sa.Integer(), nullable=True),
    sa.Column('prev_current_streak', sa.Integer(), nullable=True),
    sa.Column('prev_best_streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challengegame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challengegame_run_id'), ['run_id'], unique=False)

    op.create_table('playermatchstats',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('champion_key', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('team_kills', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('damage_to_champs', sa.Integer(), nullable=False),
    sa.Column('vision_score', sa.Integer(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('is_challenge', sa.Boolean(), nullable=False),
    sa.Column('challenge_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_game_id'], ['challengegame.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['riotmatch.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_table('poolentry',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eliminated_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('eliminated_in_game_id', sa.Integer(), nullable=True),
    sa.Column('eliminated_by_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['eliminated_by_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['eliminated_in_game_id'], ['challengegame.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'champion_id')
    )
    op.create_table('revivetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('earned_in_game_id', sa.Integer(), nullable=False),
    sa.Column('used_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('revived_champion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['earned_in_game_id'], ['challengegame.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['revived_champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revivetoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revivetoken_run_id'), ['run_id'], unique=False)

    op.create_table('spinassignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('played_champion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('played_option_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['challengegame.id'], ),
    sa.ForeignKeyConstraint(['played_champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spinassignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spinassignment_game_id'), ['game_id'], unique=False)

    op.create_table('poolevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('champion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['challengegame.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['revivetoken.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poolevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poolevent_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poolevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poolevent_run_id'))

    op.drop_table('poolevent')
    with op.batch_alter_table('spinassignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spinassignment_game_id'))

    op.drop_table('spinassignment')
    with op.batch_alter_table('revivetoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revivetoken_run_id'))

    op.drop_table('revivetoken')
    op.drop_table('poolentry')
    op.drop_table('playermatchstats')
    with op.batch_alter_table('challengegame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challengegame_run_id'))

    op.drop_table('challengegame')
    op.drop_table('appsettings')
    op.drop_table('run')
    op.drop_table('riotmatch')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_puuid'))

    op.drop_table('player')
    with op.batch_alter_table('champion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_champion_key'))

    op.drop_table('champion')
    # ### end Alembic commands ###
