"""riot sync fields

Revision ID: 0a73ed42d24d
Revises: 02d6a226e1f3
Create Date: 2026-10-05 18:45:10.628335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

import app.models  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '0a73ed42d24d'
down_revision: Union[str, Sequence[str], None] = '02d6a226e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_at', app.models.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('riotmatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_surrender', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riotmatch', schema=None) as batch_op:
        batch_op.drop_column('early_surrender')

    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.drop_column('last_sync_error')
        batch_op.drop_column('last_sync_at')

    # ### end Alembic commands ###
