"""auto matching fields

Revision ID: 773a0c0ebe84
Revises: 0a73ed42d24d
Create Date: 2026-10-05 19:09:27.652281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

import app.models  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '773a0c0ebe84'
down_revision: Union[str, Sequence[str], None] = '0a73ed42d24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challengegame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('review_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('rejected_match_ids', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challengegame', schema=None) as batch_op:
        batch_op.drop_column('rejected_match_ids')
        batch_op.drop_column('review_reason')
        batch_op.drop_column('needs_review')

    # ### end Alembic commands ###
